version: '3.7'

services:
    db:
        image: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - ./hrm-service/src/main/docker/provision/mysql:/docker-entrypoint-initdb.d
        ports:
            - '3306:3306'
        networks:
            - db
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

volumes:
    sales_data:
        driver: local
networks:
    db:
        driver: bridge