@startuml state machine
(*) --> "send command request"
--> "check if there is free a instance"
if "is there free instances?" then
    --> [true] "send command to instances"
    --> "execute command"
    --> "stream the command output to a log file"
    --> (*)
else
    --> [false] "wait"
    -> "check if there is free a instance"
endif
@enduml
