name: Plantuml generate documentation

on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]

jobs:
  ci:
    runs-on: buntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg -o "out/diagrams/" ".docs/*.puml"
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "${{secrets.username}}"
          commit_user_email: "${{secrets.email}}"
          commit_author: "Automatic ${{secrets.username}}"
          commit_message: "Generate SVG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
